site_name: Fractal Tasks Core

repo_url: https://github.com/fractal-analytics-platform/fractal-tasks-core
repo_name: fractal-tasks-core

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
    base_path:
      - fractal_tasks_core/__FRACTAL_MANIFEST__.json
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true

theme:
  name: "material"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - content.code.copy
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: light blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep purple
    accent: light blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github


nav:
  - Home page: index.md
  - Install: install.md
  - Run tasks in Fractal: tasks_in_fractal.md
  - Run tasks in Python scripts: tasks_in_scripts.md
  - Write a custom task: custom_task.md
  - Task manifest: manifest.md
  - ROI tables: roi_tables.md
  - Code reference: reference/fractal_tasks_core/
  - Development: development.md
  - Changelog: changelog.md

watch:
  - fractal_tasks_core

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: false
            docstring_section_style: "spacy"
            docstring_style: "google"
            show_source: true
            filters: []
            show_root_full_path: false
  - include-markdown

extra_css:
  - extra.css

copyright: |
  © Copyright 2022
  Friedrich Miescher Institute for Biomedical Research and
  University of Zurich
  (see <u><a href="https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/LICENSE">
  LICENSE
  </a></u>).
